# Generated by Django 5.0.7 on 2024-08-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FacultyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sl_no", models.IntegerField()),
                ("category", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("designation_and_address", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StudentMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sl_no", models.IntegerField()),
                ("name_of_student", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
            ],
        ),
    ]
