# Generated by Django 5.1 on 2024-09-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iic_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="event",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="event",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="event",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="event",
            name="description",
        ),
        migrations.RemoveField(
            model_name="event",
            name="latest_review_comments",
        ),
        migrations.RemoveField(
            model_name="event",
            name="latest_review_status",
        ),
        migrations.RemoveField(
            model_name="event",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="event",
            name="status",
        ),
        migrations.RemoveField(
            model_name="event",
            name="submission_count",
        ),
        migrations.RemoveField(
            model_name="event",
            name="type",
        ),
        migrations.RemoveField(
            model_name="event",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="event",
            name="version",
        ),
        migrations.AddField(
            model_name="event",
            name="duration",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(default="IIC-Calender Activity", max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="expenditure",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="event",
            name="external_participants",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="event",
            name="faculty",
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="event",
            name="objective",
            field=models.CharField(default="Not specified", max_length=150),
        ),
        migrations.AddField(
            model_name="event",
            name="outcome",
            field=models.CharField(default="Not specified", max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="quarter",
            field=models.CharField(default="Q1", max_length=10),
        ),
        migrations.AddField(
            model_name="event",
            name="students",
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name="event",
            name="theme",
            field=models.CharField(default="General", max_length=255),
        ),
        migrations.AddField(
            model_name="eventproof",
            name="url_reference",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(default="Seminar", max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateField(default="2024-12-31"),
        ),
        migrations.AlterField(
            model_name="event",
            name="mode",
            field=models.CharField(default="offline", max_length=50),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateField(default="2024-01-01"),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(default="Untitled Event", max_length=255),
        ),
        migrations.AlterField(
            model_name="eventproof",
            name="file_reference",
            field=models.FileField(blank=True, null=True, upload_to="proofs/"),
        ),
    ]
