# Generated by Django 5.1 on 2024-09-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("iic_app", "0002_remove_event_assigned_to_remove_event_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("seminar", "Seminar"),
                    ("webinar", "Webinar"),
                    ("Paper Presentation", "Paper Presentation"),
                ],
                default="academic",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("IIC-Calender Activity", "IIC-Calender Activity"),
                    ("Self-Driven Activity", "Self-Driven Activity"),
                    ("Celebration Activity", "Celebration Activity"),
                ],
                default="conference",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="mode",
            field=models.CharField(
                choices=[
                    ("in_person", "In-person"),
                    ("virtual", "Virtual"),
                    ("hybrid", "Hybrid"),
                ],
                default="in_person",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="quarter",
            field=models.CharField(
                choices=[("Q1", "Q1"), ("Q2", "Q2"), ("Q3", "Q3"), ("Q4", "Q4")],
                default="Q1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="theme",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("technology", "Technology"),
                    ("education", "Education"),
                ],
                default="general",
                max_length=255,
            ),
        ),
    ]
