# Generated by Django 5.1 on 2024-09-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iic_app', '0003_alter_event_category_alter_event_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='activity_guide',
            field=models.FileField(blank=True, null=True, upload_to='activity_guides/'),
        ),
        migrations.AddField(
            model_name='eventproof',
            name='promotional_platform',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eventproof',
            name='video_platform',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventproof',
            name='file_reference',
            field=models.FileField(blank=True, null=True, upload_to='media/proofs/'),
        ),
    ]
